### ISSUE TITLE
RIENumber Error

### ISSUE THREAD

**Issue by enjoylife** [kaivi/riek#13]
When using the RIENumber element an error is thrown in Chrome:

> RIEBase.js:36 Uncaught DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.

And in firefox no errors are thrown, but the input does not become editable.

**Comment by kaivi** [comment]
Hmm, in my project, the input becomes editable, but DOMException is still thrown when dealing with numeric inputs. Strange that it does not happen in [demo](http://kaivi.github.io/riek/).

**Comment by kaivi** [comment]
Okay, turns out I've merged [11](https://github.com/kaivi/riek/pull/11), but did not publish to npm. Fixed in v1.0.4.

**Comment by frnsys** [comment]
I'm still having this issue in Firefox - no errors show in the console though.
