### ISSUE TITLE
Inline style doesn't seem to work

### ISSUE THREAD

**Issue by jwyuen** [kaivi/riek#17]
When I pass in an inline style to the style prop like: 

```
            <RIEInput
                value={this.props.item.get('name')}
                style={{
                  color: itemTypeColor,
                  textTransform: 'uppercase',
                }}
                propName={"itemName"}
                change={itemNameChange}
              />
```

The color doesn't change and the text transform doesn't take effect.

**Comment by BartStout** [comment]
after textTransform: 'uppercase' you imply you are going to add another style with a ',' removing that should fix it

**Comment by jwyuen** [comment]
That doesn't seem to fix the problem for me.  It also seems like a bug that the style wouldn't apply just because of a comma dangle?

**Comment by kaivi** [comment]
For the `input` itself, pass your style inside of `editProps`. I've now added `defaultProps` for idle component in v1.0.7.

Pass the style like this:
```jsx
<RIENumber
  {...otherProps}
  editProps={ { style: { color: 'red', backgroundColor: 'yellow', width: '100%' }}}
  defaultProps={{ style: { backgroundColor: 'red', width: '100%' }}}
/>
